config/routes.rb
Rails.application.routes.draw do
  root 'articles#index'
  get 'articles', to: redirect('/')
  resources :articles, only: [:create, :new, :show] do
    resources :comments, only: [:new, :create]
    resource :upvote, only: [:create]
    resource :downvote, only: [:create]
  end
  resources :comments, only: [] do
    resources :comments, only: [:new, :create]
    resource :upvote, only: [:create]
    resource :downvote, only: [:create]
  end
  resources :users, only: [:create, :new]
  resource :session, only: [:create, :new, :destroy]
  resources :password_resets, only: [:new, :create, :edit, :update]
  

end

app/models/article.rb
class Article < ActiveRecord::Base
  include Voteable
  validates :title, :url, :user, presence: true  
  belongs_to :user
  has_many :comments, as: :commentable

  def to_s
    title
  end

  def article
    self
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  include Voteable
  belongs_to :user
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  validates :user, :commentable, presence: true

  def to_s
    text.to_s
  end

  def article
    if commentable.is_a?(Article)
      commentable
    else
      commentable.article
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :username, :email, presence: true, uniqueness: true
  has_many :articles

  def to_s
    username
  end

  def self.authenticate(email, password)
    find_by(email: email).try(:authenticate, password)
  end

  def send_password_reset_token
    self.password_reset_token = SecureRandom.urlsafe_base64
    self.password_reset_sent_at = Time.zone.now
    save!    
  end
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :voteable, polymorphic: true
  validates :user, :voteable, presence: true

  scope :for_user, -> (user) {where(user_id: user.id)}

  def upvote?
    score == 1
  end

  def downvote?
    score == -1
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  private
  def current_user
    @current_user ||= begin
      id = session[:current_user_id]
      
      if id
        User.find(id)
      end   
    end
  end
  helper_method :current_user

  def logged_in?
    current_user.present?
  end
  helper_method :logged_in?

  def require_login
    unless logged_in?
      flash[:error] = "You must be logged in to access this section"
      redirect_to articles_path # halts request cycle
    end
  end
    
  def current_user=(user)
    session[:current_user_id] = user.try(:id)
    @current_user = user
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def index
    @articles = Article.order(created_at: :desc).limit(20)
  end

  def new
    @article = Article.new
  end

  def show
    @article = Article.find(params[:id])
  end

  def create
    @article = current_user.articles.build(article_params)
    if @article.save
      redirect_to articles_path
    else
      render :new
    end
  end 

  private

  def article_params
    params[:article].permit(:title, :url)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_login, only: [:new, :create]

  def index
    @comments = parent.comments
  end

  def new
    @comment = parent.comments.build
  end

  def create
    @comment = parent.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      redirect_to @comment.article
    end
  end

  private
  def comment_params
    params[:comment].permit(:text)
  end

  def parent
    @parent ||= if params[:article_id]
      Article.find(params[:article_id])
    else
      Comment.find(params[:comment_id])
    end
  end
  helper_method :parent
end

app/controllers/downvotes_controller.rb
class DownvotesController < ApplicationController
  before_action :require_login, only: [:create]

  def create
    @vote = parent.votes.for_user(current_user).first_or_initialize
    @vote.update_attributes(score: -1)
    redirect_to :back
  end

  private
  def parent
    @parent ||= if params[:article_id]
      Article.find(params[:article_id])
    else
      Comment.find(params[:comment_id])
    end
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user
      user.send_password_reset_token
      UserMailer.password_reset(user).deliver_now
    end
    redirect_to new_session_path, notice: "Email sent with password reset instructions."
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if Time.current > @user.password_reset_sent_at + 2.hours 
      redirect_to new_password_reset_path, alert: "Password reset has expired."
    elsif @user.update_attributes(reset_params)
      redirect_to new_session_url, notice: "Password has been reset."
    else
      render :edit
    end
  end

  private
  def reset_params
    params[:user].permit(:password, :password_confirmation)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create    
    user = User.authenticate(params[:email], params[:password])
    if user  
      self.current_user = user
      redirect_to articles_path, notice: "Welcome #{user}" 
    else
      flash.now[:error] = 'Invalid email or password.'
      render :new
    end
  end

  def destroy
    self.current_user = nil
    redirect_to articles_path
  end
end

app/controllers/upvotes_controller.rb
class UpvotesController < ApplicationController
  before_action :require_login, only: [:create]

  def create
    @vote = parent.votes.for_user(current_user).first_or_initialize
    @vote.score = 1
    @vote.save
    redirect_to parent
  end

  private
  def parent
    @parent ||= Article.find(params[:article_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      self.current_user = @user
      redirect_to articles_path, notice: 'Account created.'
    else
      render :new
    end
  end

  private
  def user_params
    params[:user].permit(:username, :email, :password, :password_confirmation)
  end
end

app/helpers/votes_helper.rb
module VotesHelper
  def upvote_link(parent, user)
    vote = parent.vote_by(user)
    if vote && vote.upvote?
      'Upvoted'
    else
      link_to 'Upvote', [parent, :upvote], method: :post
    end
  end

  def downvote_link(parent, user)
    vote = parent.vote_by(user)
    if vote && vote.downvote?
      'Downvoted'
    else
      link_to 'Downvote', [parent, :downvote], method: :post
    end
  end
end

app/views/articles/index.html.erb
<h1>Index</h1>
<% if logged_in? %>
  <%= link_to("New Article", new_article_path) %>
  <br>
<% end %>

<% @articles.each do |article| %>
  <br>
  <%= article.title %>
  <br>
  <%= article.url %>
  <br>
  <%= article.user %>
  <br>
  <%= link_to("Show Article", article) %>
  <br>
<% end %>

app/views/articles/new.html.erb
<%= form_for @article do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit %>
<% end %>

<% if @article.errors.any? %>
  <% @article.errors.full_messages.each do |error| %>
    <%= error %>
    <br>
  <% end %>
<% end %>

app/views/articles/show.html.erb
<div id = "<%= dom_id(@article)%>">
  <h2><%= @article %></h2>
  <h3>Score: <%= @article.score %></h3>

  <%= link_to 'Back', articles_path %>
  <% if logged_in? %>
    <%= link_to 'New Comment', new_article_comment_path(@article) %>
    <%= upvote_link(@article, current_user) %>
    <%= downvote_link(@article, current_user) %>
  <% end %>
</div>

<br>
<% @article.comments.each do |comment| %>
  <br>
  <%= render 'comments/comment', comment: comment %>
<% end %> 

app/views/comments/_comment.html.erb
<div id="<%= dom_id(comment) %>">
  <%= comment.user %>
  <br>
  <%= comment %>
  <br>
  Karma: <%= comment.score %>
  <br>
  Posted <%= time_ago_in_words(comment.created_at) %> ago
  <br>
  <% if logged_in? %>
  <%= link_to 'Reply', new_comment_comment_path(comment) %>
  <%= upvote_link(comment, current_user) %>
  <%= downvote_link(comment, current_user) %>
<% end %>
</div>

<ul>
<% comment.comments.each do |child| %>
  <br>
  <li>
  <%= render 'comments/comment', comment: child %>
  </li>
<% end %>
</ul>

app/views/comments/_view.html.erb
<%= comment.user %>
<br>
<%= comment %>
<br>
Posted <%= time_ago_in_words(comment.created_at) %> ago
<br>
<%= link_to 'Reply', new_comment_comment_path(comment) %>
<br>

app/views/comments/new.html.erb
<h3>New Comment</h3>
<%= form_for [parent, @comment] do |f| %>
  <%= f.label :text %>
  <%= f.text_field :text %>
  <%= f.submit %>
<% end %>

<% if @comment.errors.any? %>
  <% @comment.errors.full_messages.each do |error| %>
    <%= error %>
    <br>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Haxxor</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1><%= link_to("Haxxor News", articles_path) %></h1>

<% if logged_in? %>
  <%= link_to("Log out", session_path, method: :delete) %>
<% else %>
  <%= link_to("Create an Account", new_user_path) %>
  <%= link_to("Log in", new_session_path) %>
<% end %>
<br><br>

<% flash.keys.each do |key| %>
  <div class="flash <%= key %>"><%= flash[key] %></div>
<% end %>

<%= yield %>

</body>
</html>

app/views/password_resets/edit.html.erb
<h1>Reset Password</h1>
<%= form_for @user, url: password_reset_path(params[:id]) do |f| %>
  <% if @user.errors.any? %>
    <% @user.errors.full_messages.each do |error| %>
      <%= error %>
      <br>
    <% end %>
  <% end %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation, 'Confirm password' %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit "Update Password" %>
<% end %>

app/views/password_resets/new.html.erb
<h1>Reset Password</h1>
<%= form_tag(password_resets_path) do %>
  <%= label_tag :email %>
  <%= text_field_tag :email, params[:email] %>
  <br>
  <%= submit_tag "Reset Password" %>
<% end %>

app/views/upvotes/create.html.erb
<h1>Upvotes#create</h1>
<p>Find me in app/views/upvotes/create.html.erb</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <br>
  <%= f.label :password_confirmation, 'Confirm password' %>
  <%= f.password_field :password_confirmation %>
  <br>
  <%= f.submit %>
<% end %>

<% if @user.errors.any? %>
  <% @user.errors.full_messages.each do |error| %>
    <%= error %>
    <br>
  <% end %>
<% end %>